package config

var Config = map[string]string{
	"PORT":                   "8080",
	"JWT_KEY":                "5201314",
	"ADMIN_NAME":             "",
	"GPT_ASST_ID":            "",
	"SSL_ENABLE":             "false",
	"SSL_CERTIFICATE":        "cert.pem",
	"SSL_KEY":                "key.pem",
	"DB_USER":                "floodguard",
	"DB_PORT":                "3306",
	"DB_HOST":                "localhost",
	"DB_NAME":                "floodguard",
	"DB_PASSWORD":            "floodguard",
	"SMTP_SERVER":            "",
	"SMTP_PORT":              "25",
	"SMTP_MAIL":              "",
	"SMTP_PASSWORD":          "",
	"PERMISSION_USER":        "false",
	"PERMISSION_REGION":      "false",
	"PERMISSION_FLOODEVENT":  "false",
	"PERMISSION_HISTORYDATA": "false",
	"PERMISSION_NOTICE":      "false",
	"PERMISSION_COMMENT":     "false",
	"PERMISSION_SENSOR":      "false",
}
